**Считываем данные из файла train.csv с помощью библиотеки pandas**

In [1]:
import pandas as pd

df = pd.read_csv(r'C:\Users\Gleb\Desktop\Итмо\Основы Питона\train.csv').sort_values(by = 'Age', ascending = False)
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
745,746,0,1,"Crosby, Capt. Edward Gifford",male,70.0,1,1,WE/P 5735,71.0000,B22,S
672,673,0,2,"Mitchell, Mr. Henry Michael",male,70.0,0,0,C.A. 24580,10.5000,NaN,S
33,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S
456,457,0,1,"Millet, Mr. Francis Davis",male,65.0,0,0,13509,26.5500,E38,S
54,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,B30,C

**Основное инфо**

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 891 entries, 630 to 888
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 90.5+ KB

In [3]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [4]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

**Процент выживаемости по классам пассажиров**

In [5]:
unique = (df['Pclass'].unique())
unique

array([1, 3, 2])

In [6]:
survival_by_class = df.groupby('Pclass')['Survived'].mean() * 100
survival_by_class

Pclass
1    62.962963
2    47.282609
3    24.236253
Name: Survived, dtype: float64

**популярное мужское и самое популярное женское имя на корабле**

In [7]:
# имя в скобках
name_in_brackets = df['Name'].str.extract(r'\(([^ ]+)')

# имя после титула
name_after_title = df['Name'].str.extract(r',\s*[^\.]+\.\s*([A-Za-z]+)')

# итоговое имя
df['FirstName'] = name_in_brackets[0].fillna(name_after_title[0])

male_name = df[df['Sex'] == 'male']['FirstName'].value_counts().idxmax()
female_name = df[df['Sex'] == 'female']['FirstName'].value_counts().idxmax()

print('Самое популярное мужское имя:', male_name)
print('Самое популярное женское имя:', female_name)

Самое популярное мужское имя: William
Самое популярное женское имя: Anna

**популярное мужское и самое популярное женское имя на корабле в каждом классе**

In [8]:
for pclass in sorted(df['Pclass'].unique()):

    subset = df[df['Pclass'] == pclass]

    male_name = subset[subset['Sex'] == 'male']['FirstName'].value_counts().idxmax()
    female_name = subset[subset['Sex'] == 'female']['FirstName'].value_counts().idxmax()

    print(f'Класс {pclass}')
    print(f'Мужское имя: {male_name}')
    print(f'Женское имя: {female_name}')
    print()

Класс 1
Мужское имя: William
Женское имя: Elizabeth

Класс 2
Мужское имя: William
Женское имя: Elizabeth

Класс 3
Мужское имя: William
Женское имя: Anna

**Пассажиры старше 44 лет**

In [9]:
df[df['Age'] > 44]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FirstName
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S,Algernon
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S,Johan
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C,Ramon
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C,George
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q,Patrick
...,...,...,...,...,...,...,...,...,...,...,...,...,...
440,441,1,2,"Hart, Mrs. Benjamin (Esther Ada Bloomfield)",female,45.0,1,1,F.C.C. 13529,26.2500,NaN,S,Esther
706,707,1,2,"Kelly, Mrs. Florence ""Fannie""",female,45.0,0,0,223596,13.5000,NaN,S,Florence
856,857,1,1,"Wick, Mrs. George Dennick (Mary Hitchcock)",female,45.0,1,1,36928,164.8667,NaN,S,Mary
62,63,0,1,"Harris, Mr. Henry Birkhardt",male,45.0,1,0,36973,83.4750,C83,S,Henry
187,188,1,1,"Romaine, Mr. Charles Hallace (""Mr C Rolmane"")",male,45.0,0,0,111428,26.5500,NaN,S,"""Mr"

**Мужчины младше 44**

In [10]:
df[(df['Age'] < 44) & (df['Sex'] == 'male')]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FirstName
668,669,0,3,"Cook, Mr. Jacob",male,43.00,0,0,A/5 3536,8.0500,NaN,S,Jacob
314,315,0,2,"Hart, Mr. Benjamin",male,43.00,1,1,F.C.C. 13529,26.2500,NaN,S,Benjamin
818,819,0,3,"Holm, Mr. John Fredrik Alexander",male,43.00,0,0,C 7075,6.4500,NaN,S,John
699,700,0,3,"Humblen, Mr. Adolf Mathias Nicolai Olsen",male,42.00,0,0,348121,7.6500,F G63,S,Adolf
349,350,0,3,"Dimic, Mr. Jovan",male,42.00,0,0,315088,8.6625,NaN,S,Jovan
...,...,...,...,...,...,...,...,...,...,...,...,...,...
305,306,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S,Hudson
78,79,1,2,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,29.0000,NaN,S,Alden
831,832,1,2,"Richards, Master. George Sibley",male,0.83,1,1,29106,18.7500,NaN,S,George
755,756,1,2,"Hamalainen, Master. Viljo",male,0.67,1,1,250649,14.5000,NaN,S,Viljo
803,804,1,3,"Thomas, Master. Assad Alexander",male,0.42,0,1,2625,8.5167,NaN,C,Assad

**Кол-во n-местных кабин**

In [11]:
cabins = df['Cabin'].dropna()
cabins_count = cabins.str.split().apply(len).value_counts()
cabins_count

Cabin
1    180
2     16
3      6
4      2
Name: count, dtype: int64

**Пассажиры без родственников на борту**

In [12]:
no_relatives = df[(df['SibSp'] == 0) & (df['Parch'] == 0)]
len(no_relatives)

537